### ISSUE TITLE
Not able to download the pre-generated data

### ISSUE THREAD

**Issue by dschaehi** [princeton-vl/Rel3D_Render#1]
Thank you for the interesting work and setting up this repository. I am currently trying to download the pre-generated data
using the given link (https://drive.google.com/uc?id=1MSMwnX0znCfgEisj7zJ4ohFWJDrsxeme) but am not able to download it. Could you check whether the link is working? I get the following message every time I tried to access the link:

> Sorry, you can't view or download this file at this time.

> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by imankgoyal** [comment]
Thanks for you interest in our work. Apologies for the late response. Somehow I missed this issue. I checked and the link is working fine.

**Comment by dschaehi** [comment]
Thanks for your reply. I managed to download the data. The only thing I had to do was to log in to my Google account. If this is a necessary step to download the data, then you could perhaps mention this in the README (perhaps, you could try to download the data in private mode of your browser without logging in to your Google account).

**Comment by imankgoyal** [comment]
Thank you so much for that information. I updated the README.
